### ISSUE TITLE
Request How-To Notes for Root CA Refresh

### ISSUE THREAD

**Issue by sproggit** [texadactyl/diyca#18]
**Is your feature request related to a problem? Please describe.**
Very happy DIYCA User here... been running flawlessly on my RPi4 since November 2019... but I imported my Calvin root Cert to a new home machine this weekend and noticed that it will expire in November this year [2 year lifespan]. 

**Describe the solution you'd like**
Would it be possible to extend the documentation to show how to create a new root certificate please? Also, very conscious that the codebase hasn't been touched since installation time in 2019... it looks from a cursory read of the instructions that the way to upgrade to the latest version might be to wipe and start over? Should I be concerned about migrating to the latest version? 

**Describe alternatives you've considered**
N/A

**Additional context**
Happy to provide any other documentation or information that may be required.

**Comment by texadactyl** [comment]
Excellent issue - thanks.
A fix will not be difficult but requires more research into best practices.

**Comment by texadactyl** [comment]
While your suggestion for automating the creation of a new CA certificate is valid, I cannot reproduce your results.  When I examine the CA certificate after initialization, I see this:

```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            38:38:31:97:e9:a5:7a:b2:85:a2:34:b9:a4:54:22:31
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=CAintranet Org, OU=CAintranet Staff, CN=CAintranetCommonName
        Validity
            Not Before: Apr  8 18:36:50 2021 GMT
            Not After : Apr  6 18:36:50 2031 GMT
```
etc.

The lifetime of this certificate is 10 years.  This matches the configuration file (diyca_calvin_cert.cfg) parameter:
```default_days            = 3650```

Is it possible that whatever security system you imported it to somehow has overriden the expiry date?

**Comment by sproggit** [comment]
And it would have taken me a month of Sunday's to get to the bottom of that, but, yes, that was the issue. Trying to test what is I believe hoped to be an open source alternative to Azure's "Service Bus" - which itself is a borderline rip-off of IBM's "WebSphereMQ" Messaging platform. I was authenticating between queue managers for an encrypted channel, and the software was conflating the timestamp of the actual cert with the imported root. So the expiry I was seeing in configuration options was not the root cert's details, but an endpoint cert. 

False alarm. 

Very (very) sorry to have troubled you.

**Comment by texadactyl** [comment]
Not trouble at all.  

The application (endpoint) expiry is, in fact, 2 years.  Unfortunately, hard-coded to:
```EXPIRY_PERIOD = 60*60*24*365*2   # 2 years```
in ```app_web/diyca_web_signer.py```.

Would you like this to be more easily edited?

**Comment by texadactyl** [comment]
Keep in mind, this repository is to be used for development or testing ONLY.  Do not use it in production.
