### ISSUE TITLE
Need to update cert generations given enhanced browser security (Good job and thank you, Firefox and Google!)

### ISSUE THREAD

**Issue by sproggit** [texadactyl/diyca#24]
**Describe the bug**
I am not sure if this is a bug or an idiot user. 

Symptoms: Having created and deployed a DIYCA-signed certificate to a local web server (Apache2 running on an RPi4B, to host WordPress and NextCloud for family use) I see an error from Firefox (104.0.2, Linux, 64-bit) when I first access any DIYCA-protected web site. The "error" is a FireFox message, "Warning: Potential Security Risk Ahead", with Error code: "SSL_ERROR_BAD_CERT_DOMAIN". 

This is a relatively recent change in behaviour - when I first set up this site, I did not observe this error. Research leads me to believe this might be related to changes in Firefox, but I think that Firefox may be generating an error based on discrepancies it thinks it sees in DIYCA-generated certificates. But I'm not sure of that. See attached "ErrorGenerationSteps.txt" for more details. 

Please see attached file, "000 - On-Screen Error as seen in browser.png" for actual render of message... 

![000 - On-Screen Error as seen in Browser](https://user-images.githubusercontent.com/4345422/189585193-8103eebc-0b3d-461f-b7c8-23a6879e6217.png)

If I then choose to view the certificate, this is what I see:-

![001 - View of Certificate from Firefox Error Page](https://user-images.githubusercontent.com/4345422/189585236-d7868b91-3beb-4801-928d-52e76fc4fd59.png)

I am able to bypass/ignore this "bug" simply by selecting "Accept the Risk and Continue", but would obviously like to eliminate that if I can... 

I suspect/wonder (but do not know) if the issue might be related to DIYCA's root CA? 

**To Reproduce**

I want to be detailed in terms of the steps I took to reproduce this error, including details regarding the generation of the CSR using the OpenSSL utility and the way I have this deployed with Apache2, so I put more detailed notes in this TXT file:-
[ErrorGenerationSteps.txt](https://github.com/texadactyl/diyca/files/9545039/ErrorGenerationSteps.txt)

**Expected behavior**
Ideally, I would like to be able to navigate to a URL protected by a DIYCA server and have the browser accept the certificate without error and take me to the site directly. 

**Screenshots**
One more screen shot for you... here's a view of my Firefox "Certificate Store", showing the DIYCA Root Certificate successfully imported:-
![002 - Proof of DIYCA Root Cert in Browser](https://user-images.githubusercontent.com/4345422/189585681-7800f157-cad4-4a16-9c3d-2dcdf02c8cd2.png)

**Desktop (please complete the following information):**
 - OS: Mint Linux 20.1 Ulyssa, Kernel 5.15-0-46-generic-x86_64
 - Browser: Firefox 
 - Version: 104.0.2

**Additional context**
I have changed my local network to Class-B Address 172.16.*.* to allow me to use address ranges to identify devices.
I have deployed Pi-Hole DNS Sink to provide local DNS Services and add/manage my own local DNS records for access to local resources (e.g. the certificate in question is "nc2.saurian.net" for NextCloud Server 2...) Don't think this should be impactful, but you never know... 

Obviously entirely happy to provide more details if required. 

Thank you.

**Comment by sproggit** [comment]
Brief update. 
I have now had a chance to re-test the error-generating certificate using Microsoft Edge on Windows 10 and observe the same problems that I was seeing when using Firefox on Mint... This still isn't sufficient to be conclusive as to root cause, but I think it might help eliminate browser/OS from the equation. 

When I did the Windows test, I only went as far as importing the Calvin cert into Edge, I did not add it to Windows, so I got a follow-on error concerning that discrepancy... but the rest of the process did not show the original error.

**Comment by texadactyl** [comment]
Obviously, there is ZERO risk for you as this is a LAN-based tool for local-only developers to get used to operating with user/application (E.g. web server) certificates signed by a simulated CA (Calvin).  Once those applications are ready, it is expected that the admin will get a user/application certificate signed by conventional CA such as Thawte ($$) prior to rolling out beyond developer-testing (E.g. QA, production).

Linux, here.  I have reproduced your symptoms in Firefox.  I also get a warning in Chrome.  In both cases, I can get to the web server if I "accept the risk".  You can safely do so as you are connecting to something totally under your control and the diyca code is open source.

I don't have access to MacOS or Windows.

This is happening due to an understandable perceived security risk (and Good Job!!) as Calvin (simulated CA) is self-signed and the web server does not have a DNS name.  Two issues.  I will need some time to explore potential work-around solutions.

**Comment by texadactyl** [comment]
https://www.chromium.org/Home/chromium-security/root-ca-policy/

**Comment by texadactyl** [comment]
@sproggit , I have it working with no nasty remarks from Firefox and Chrome.  Sorry, no access to Windows or MacOS.

Please consider reinstalling or doing a ```git pull```.
The software version is now included in the log file.

BEFORE starting the web server, 
* Make sure that it is using a cert that has an IP address that matches what is specified in ```bin/diyca_web_cert.cfg```.
* The web server's cert should be recreated with ```bin/3.diyca_web_init.sh```.
* When in doubt, start over with a reinstall but that may be inconvenient.

Please let me know of your progress.

**Comment by sproggit** [comment]
Hello,
I am sorry that it has taken me four days to get the time to test and post a reply, especially given how quickly you responded and offered fixed code. 

I can confirm that everything appears to be working perfectly (just one test so far). 

Given the near-infinite flexibility of Raspberry Pi computers (one MicroSD card == one build) I was able to simply create a brand new RaspiOS image, boot that using the "plumbed in" hardware normally allocated to my local Calvin CA and then basically create a brand new build. 

I have just cut a brand new CSR for the house WordPress web server and used that to sign up a web cert - deployed and with the new root cert added to my local FireFox and everything has worked beautifully. 

I would like to say a sincere "thank you" for responding so quickly with a flawless solution. 

One hugely positive improvement this has given me as been for my experimental NextCloud setup. I use this, in conjunction with the "Floccus" browser plug-in, so that everyone at home can sync their bookmarks across all devices. It turns out that Floccus uses WebDAV to manage updates to the central bookmark repository held in NextCloud, so because I run devices over wifi, I've got NextCloud set up to use TLS and one of Calvin's certs). What I've discovered is that, thanks to this browser tweak, Floccus is broken by default with the old-style certs. You can over-ride this if you simply open a browser session, point to the NC instance and then accept the "bad" SSL cert for the session... but FireFox won't let you remember that "accept". 

Fortunately, the fix you've provided means that I can re-secure everything on the home network again. 

Really appreciate the prompt response. 

Thank you.

**Comment by texadactyl** [comment]
@sproggit  Thanks for the good news.
