### ISSUE TITLE
New Variation of Defect #24 ("Enhanced" Browser Security), now with Firefox 105.0.3

### ISSUE THREAD

**Issue by sproggit** [texadactyl/diyca#26]
**Describe the bug**
With sincere apologies, I am afraid that I have to report what looks to be the re-emergence of defect #24, this time with Firefox 105.0.3.

As reported for my testing of the fix for defect #24, at that time I created a new certificate for my domestic WordPress environment. That functioned perfectly. Today I went back and created an all-new certificate, using the brand new DIYCA installation, for my NextCloud environment. 

To my surprise, I saw that I was getting the same Bad_Cert_Domain error that I had previously reported. 

My default assumption was, "idiot user"... but when I checked my access to my local family "WordPress"  site, which had previously been tested and which had worked perfectly with the latest edition of DIYCA, I see that the same error has returned. 

However, one thing which has changed is my browser, since Mint Update gave me Firefox 105.0.3 - replacing 105.0.2 - first thing this morning. Given the observed failure modes - previously working site now not working immediately after a Firefox update - my inclination is to suggest that this is a variation of the issue we observed last time [i.e. Firefox raising the security bar for certificates]. But I accept that my evidence is a bit thin on the ground. 

As before, very happy to provide support, more evidence, copies of pem/key/csr/crt files, should that help diagnosis. 

Very sorry to put you to the trouble.

**Comment by texadactyl** [comment]
I followed the installation notes in a fresh environment.
Sorry but I cannot reproduce this with Firefox 105.0.3.

After the Firefox upgrade, 
* Is the Calvin trusted CA cert still in the Firefox settings repo?
* Did anything else change on your machine?
* Did you launch this way?  https://192.168.1.104:8080   (Substitute your configured IP address and port)

**Comment by sproggit** [comment]
1. Is the Calvin trusted CA cert still in the Firefox settings repo?
I checked and in fact I found 2 Calvin Trusted CA certificates ["old" and "new" versions, which both appear with the same labels]. To be safe I removed both and then re-imported the new one, but I saw no difference in performance. 

2. Did anything else change on your machine?
I'm tempted to say "No"... but I want to check. I haven't made any user-side configuration changes, but I do keep system updates running quite regularly. Fortunately the Mint Updater gives a good account for itself. I will need to dig back through the logs and check, however, so I will do that. 

3. Did you launch this way? https://192.168.1.104:8080/ (Substitute your configured IP address and port)
I have a horrible feeling that I did not, so this is something else I am going to need to check. I have a bookmark for the CA on my toolbar, but it has captured, "https://ca.saurian.net/:8080" as the URL (saurian.net being the org name I use on my home network - *not* the publicly visible one). Just to be on the safe side, I think it will be a good idea for me to re-cut this certificate using the IP address rather than the URL. 

Sorry that this is a flying visit - I did not want you to think I was ignoring you when you were kind enough to check and respond to me. I won't get a chance to check tonight, but will aim to test tomorrow and report back. 

Thanks again for all your kind support - it is much appreciated.

**Comment by texadactyl** [comment]
I have not tested in an environment that uses a local DNS server.  Clearly, ```https://ca.saurian.net``` gets mapped by your local DNS server into an appropriate local IP address.

As stated in the preparation notes
- The ```subjectAltName``` value in the web server certificate must precisely match the URL specified in the browser location window.  
- The web server certificate is created based on ```diyca_web_cert.cfg``` during execution of the ```3.diyca_web_init.sh``` bash script.

**Comment by texadactyl** [comment]
@sproggit You must have an update by now.

**Comment by texadactyl** [comment]
@sproggit Closing this now. Open a new issue if you are having difficulties.

**Comment by sproggit** [comment]
Richard, I'm really sorry for the radio silence. My Father passed away unexpectedly and - to keep it simple - pretty much everything that could go wrong has gone wrong. Currently battling with banks, lawyers, angry relatives; you name it - if it could have gone wrong, it has gone wrong. 
Sat down today for the first time in three or more weeks with the intent of allowing myself a couple of hours of "me" time... Discovered that my domestic NextCloud instance had an update pending; applied that and the update script completed - apparently - but has trashed the instance completely, so now I need to do a clean installation of that. It was just too much to face today. 
Thanks for closing this - entirely correctly - and I will get a working host back up and running and then test again, as you suggested, with basic IP addresses. 
Thank you

**Comment by texadactyl** [comment]
@sproggit 
Don't sweat the small stuff.  Family and other real life come first.

**Comment by sproggit** [comment]
OK... Firstly, I'm very sorry that it has taken me so long to get back and report on the results of creating a fresh installation and double-checking the elements that you asked me to verify. This time, hopefully, I come with better information. 

Firstly, I am still seeing an error, but... I am able to access the Calvin/DIYCA web site, using:-

https://172.16.103.4:8080

which is the IP address of the Calvin CA. When I use the above URL, I get perfect access, without any issues, without any reported warnings. (Obviously I've created a new Calvin Root Cert, removed the old one from Firefox and replaced it with this latest copy. 

I was especially careful to check every step of the instructions and I attach for reference the various files that the installation process asks to be customized. I also attach a screen scrape - and I'm sorry, I do appreciate it likely won't be too helpful, showing the error I'm still seeing. 

Lastly, I know this is a minor thing and I'm > 95% confident it has no bearing, but when I got to the step in the installation process where I am asked to "sudo systemctl enable rc-local.service", I see an error which I found being reported by other people (for different applications...) However, when then reboot my Pi and check, I see that DIYCA's web server has auto-started, so I think that might be a false alarm. Out of an abundance of caution, though, here's a transcript of what I see on screen:-

**```
root@raspberrypi:/opt/diyca# sudo systemctl enable rc-local.service
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
root@raspberrypi:/opt/diyca#
```** 

![Screenshot from 2023-05-08 19-19-55](https://user-images.githubusercontent.com/4345422/236904381-74f0add3-8271-4c7e-89cc-4440bce2729d.png)
![Screenshot from 2023-05-08 19-20-17](https://user-images.githubusercontent.com/4345422/236904394-3248d6af-b69b-4245-bafb-04a9e375426e.png)

-=-=-=-=-=
Turns out that I'm not able to upload a file of type .cfg, so I can't attach the "diyyca_web_cert.cfg" file, so instead I'll simply paste it here. 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[req]
prompt = no
distinguished_name = dn
req_extensions = ext

[dn]
CN = CA web server
C = US
ST = Montana
L = Billings
OU = CAintranet Staff
O = CAintranet Org
emailAddress = diyca.web.server@somewhere.net

[ext]
subjectAltName = IP:172.16.103.4
#########           ^^^^^^^^^^^^^
#########
######### The browser must specify the above IP address + the port number 
######### that the web server is listening to at that location (host)
#########
######### E.g. In the browser, specify https://192.168.1.102:32767
######### assuming the above IP address (192.168.1.102)
######### and that the port number used by the DIYCA web server = 32767
######### (PORT assigned in app_web/diyca_web.cfg)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The result of the test is that I continue to see a consistent Cert warning when using a Calvin cert with Apache2 and NextCloud on a Raspberry Pi, but it seems to work perfectly with the DIYCA web server (on a different Pi). 

This strongly suggests that the problem is "idiot user", most likely down to a selection of incorrect parameter settings, but for the life of me I can't see what I've done. 

Always happy to experiment and/or share more files if that would be of help. 

Thanks in advance for any suggestions as to the cause.

**Comment by texadactyl** [comment]
**What was the exact cert warning?**  My guess is that your Apache system does not like relying on certificates with IP addresses; it probably wants a DNS name or Calvin's CA cert placed in a trust store on your system. However, you stated that it worked anyways. Been there; done that.

Remember: diyca is intended for use by software developers that want to get their feet wet with digital certificates.  So, using IP addresses or DNS names in a particular CA's certificate is transparent to their source code. It is assumed that their code will be rolled out to a quality assurance environment prior to production and their application (user) certificates will be signed by web-trusted CAs like Verisign or Symantec.

For the future, any text file that you cannot upload, just rename with a .txt on the end -or- zip it up and attach either a tar.gz or .zip file.

**Comment by texadactyl** [comment]
Yes, I get the same ugly response to "sudo systemctl enable rc-local.service".  The operative phrase from the preparation notes is "You may need to enable rc.local compatibility".  SInce it auto-starts as you said, I guess it is not necessary, especially since there seems to no longer be such a systemctl service.

I'll fix the preparation notes again. Moving target! (-:

**Comment by texadactyl** [comment]
A bit more on your apache server.  

This is your "user application". You must have generated a CSR and Calvin signed it, yes? The more I think of it, the more I believe that you just need to place Calvin's CA cert in a trust store and apache's signed cert wherever apache SSL wants it. Then,
* When apache comes up, it should be happy with its "user application" certificate because it was signed by a trusted CA (Calvin).  
* The browsers will trust apache because apache's cert was signed by Calvin (trusted in the browser).

Make sense?

**Comment by sproggit** [comment]
Hello Richard... I think I have one more suggestion for your preparation notes. 
And yes, I managed to figure out where I was going wrong. 

The first change I made was to my Apache2 "Site" file in /etc/apache2/sites-available. I added a new line of detail:-

SSLCertificateChainFile /var/ssl/diyca_calvin.crt

This was my attempt to follow your advice regarding making Calvin's self-signed cert visible to Apache. I restarted Apache, but this made no difference. However, I'm including it here because I don't know that the next step would have worked without it... 

I did a bit more digging, looking back to the versions of Firefox that I was running when I spotted the problem, which was 101.0. I discovered that although the "CA Browser Forum Baseline Requirements" had required the presence of "subjectAltName" in certificates since 2012, Mozilla had, up until 101.0, accepted CN matching as an alternate. It then deprecated this legacy support, which was when I saw the problem emerge. 

From this suspicious timing, I came to the conclusion that my intended "Alt Name" for my web site was not being picked up when I ran the "openssl" CSR generation step, so I took a look at Calvin's config file, read around the web a bit, then created a config file, as follows:-

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[req]
default_bits = 2048
prompt = no
distinguished_name = dn
req_extensions = ext

[dn]
CN = NextCloud Server
C = GB
ST = Hampshire
L = Groupware
OU = Groupware
O = Saurian Org
emailAddress = nc@{mydomain}.org

[ext]
subjectAltName = @alt_names

[ alt_names ]
DNS.01 = nc.{mydomain}.net
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

That gave me a _different_ CSR when I ran a simple "diff" at the command line, so I submitted that through CALVIN and I've added that to my Apache web site and tested and confirmed it is working.


I'm going to stand by my original "idiot user" diagnosis... I think I was overly reliant upon documentation I had written for myself when I first started using openssl - applying the "if it ain't broke, don't 'fix' it" mindset - and that is where I tripped myself up. 

Now, you already had this requirement (AltName) documented in your instructions and I had thought that my command line parameters were good, but clearly not. So perhaps a word of warning might help others to avoid this particular gotcha. 

Thank you - again - for your time, support and patience. Very much appreciated

Clive

**Comment by texadactyl** [comment]
The above makes sense to me.  Does the following make sense to you?

See : http://slacksite.com/apache/certificate.html

```ssl.conf``` sample:
```
<IfDefine SSL>

<VirtualHost _default_:443>
ServerAdmin   webmaster@domain.com
DocumentRoot   /usr/local/apache/share/htdocs
ServerName   www.domain.com
ScriptAlias   /cgi-bin/   /usr/local/apache/share/htdocs/cgi-bin/
SSLEngine   on
SSLCertificateFile    /usr/local/apache/etc/ssl.crt/server.crt
SSLCertificateKeyFile   /usr/local/apache/etc/ssl.key/server.pem
SSLCertificateChainFile   /var/ssl/diyca_calvin.crt
SetEnvIf   User-Agent   ".*MSIE.*"   nokeepalive   ssl-unclean-shutdown
CustomLog   /usr/local/apache/var/log/ssl_request_log \
        "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
</VirtualHost>

</IfDefine>
```

SSLCertificateFile = the web server's certificate file signed by a trusted CA (E.g. Calvin).

SSLCertificateKeyFile = the web server's PRIVATE key file in PEM format that was generated.  This should be found in /WHEREVER/diyca/app_web/private/.  E.g. I just generated everything and I can see ```diyca_web.key``` in the ```private``` directory.

SSLCertificateChainFile = a bundle of certs for trusted CAs. However, you can just point at Calvin as you have said.

```=====================================================================```

How are you doing now?

**Comment by texadactyl** [comment]
So long as apache has a user cert signed by Calvin and all the browsers trust Calvin, then all the browsers should play nicely with apache.

**Comment by sproggit** [comment]
Yes, the example does make good sense to me. There are a couple of change I would probably want to make that have become a bit more relevant in recent years... for example I would probably want to add:-

SSLProtocol -all +TLSv1.2 +TLSv1.3

to force browsers to use a more recent and more secure version of TLS... It doesn't necessarily have to be "the most recent" version, just so long as there is some form of assertive control so that you know what you're working with, as opposed to leaving components to pick their own defaults. I guess that's why my fstab NFS options always include "nfsvers=4" in there, too. 

I think that, _"So long as apache has a user cert signed by Calvin and all the browsers trust Calvin, then all the browsers should play nicely with apache"_ is pretty much where it's at. It would be nice to throw up a test virtual Apache instance, drop the "SSLCertificateChainFile" reference and see if that makes a difference. In the earlier working setup - before this round of trouble - that would have worked perfectly... but I think you make a very important point when you write the above...

After all, the entire point of having a PKCS-protected infrastructrure is so that the participants can trust one another. 

...
As for the rest... well, spent the last few months metaphorically bending over backwards trying to 'keep the peace'... wasn't too successful, so gently and politely stepped back and left everyone to it. That quickly resulted in 'family world war', which apparently was all my fault for deciding I didn't need the abuse. As a result I've been disinherited and nobody is speaking to me. You have no idea how sanguine I feel about that... 

...
Thanks again for your patience. 
I can always tell when things are looking up - the urge to tinker with new tech returns!!   ;o)

**Comment by texadactyl** [comment]
Peace be with you.
