### ISSUE TITLE
Duplicate Serial numbers in the certificates

### ISSUE THREAD

**Issue by au-squirrel** [texadactyl/diyca#6]
I signed multiple certificates using the CA. All had the serial number of 42. While that is the meaning of life, firefox and chrome detect the same serial number on multiple certificates and error. I used your CA to sign my certificates I generated for the cockpit web based remote administration system.

Relevant section of code from app_web/diyca_web_signer.py
 try:
                cert = crypto.X509()
                cert.set_serial_number(42) <-------------------------------
                cert.gmtime_adj_notBefore(0)
                cert.gmtime_adj_notAfter(EXPIRY_PERIOD)
                cert.set_issuer(CAcertificate.get_subject())
                subject = csr.get_subject() # will log the subject later
                cert.set_subject(subject)
                cert.set_pubkey(csr.get_pubkey())
                cert.sign(CAprivatekey, DIGEST)
        except Exception as e:
                app.logger.error("sign_csr: Cannot sign CSR {%s} for user {%s}, reason: {%s}", arg_csr_path, arg_userid, repr(e))
                return False
        # Store signed CRT

This should be imported from the file /opt/diyca/calvin/db/serial and then incremented or left to the openssl CA function. The results in the certificates are:
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 42 (0x2a)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, O = SqXXXs Org, OU = SqXXXs Admin, CN = sXXXXs.id.au
        Validity
            Not Before: Mar 27 12:42:38 2019 GMT
            Not After : Mar 26 12:42:38 2021 GMT
        Subject: C = AU, ST = Queensland, L = Samford Valley, O = sXXXs, CN = cosmos.sqXXXs.id.au, emailAddress = nXXXl@XXXXXXXXX
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 42 (0x2a)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, O = SqXXXs Org, OU = SqXXXs Admin, CN = sqXXXs.id.au
        Validity
            Not Before: Mar 27 09:46:15 2019 GMT
            Not After : Mar 26 09:46:15 2021 GMT
        Subject: C = au, ST = Queensland, L = Samford Valley, O = sXXXs, CN = certis.sqXXXs.id.au, emailAddress = neil@squires.id.au
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
Based on the config for the openssl 
[ca_default]
home                    = .
database                = $home/db/index
serial                  = $home/db/serial
crlnumber               = $home/db/crlnumber

**Comment by texadactyl** [comment]
Thank you for your feedback.

Should be easy to fix and still keep the project simple. Where the serial number is supplied, I could insert the number of seconds since epoch plus a random number. I might have to hash the result to make it fit in the field.

Currently, I am out of my house until the destruction phase of my home remodeling is complete. So, its hard to work on this. I should be back inside by this coming Monday.

**Comment by au-squirrel** [comment]
Here is my hack that I did to use the calvin/db/serial file. Apologies if it is not as tidy as I and you would like and I have not included all the possible error handling for the files, but it is working. I also modified the get_serial as I was not processing the returned tuple correctly. I will have a better look over the weekend and figure it out.

Feel free to use/modify or discard it.

import os
from OpenSSL import crypto
from flask import current_app as app

CA_CRT_FILE = "../certs/diyca_calvin.crt"
CA_KEY_FILE = "../calvin/private/diyca_calvin.key"
SERIAL_FILE = "../calvin/db/serial"

EXPIRY_PERIOD = 60*60*24*365*2   # 2 years
DIGEST = "sha256"

#=================================================================
# Retrieve the contents of a file and return it as a string
#
# Returns
#   True/False: Success or failure
#   str:        file contents (success) or exception info(failure)
#=================================================================
def get_file_contents(arg_path):
    try:
        file = open(arg_path, "r")
        text = file.read()
        file.close()
        return (True, text)
    except Exception as e:
        return (False, repr(e))

#=================================================================
# Get the current serial number then increment it by 1
#
#Returns
#       True/False:     Success or Failure
#       int:            Current serial number
#       file output:    Increments the file /opt/diuyca/cavlin/db/serial by 1
#
#=================================================================
def get_serial():
        try:
                serial_file = open(SERIAL_FILE, "r+")
                serial_text = serial_file.read()
                serial_no = int(serial_text)
                serial_file.seek(0)
                serial_file.write(str(serial_no + 1))
                serial_file.close()
                return (serial_no)
        except  Exception as e:
                return( False, repr(e))


#=================================================================
# Sign a CSR file for the given user,
# storing the result in the CRT file
#
# Returns
#   True/False: Success or failure
#=================================================================
def sign_csr(arg_userid, arg_csr_path, arg_crt_path):
    # csr = User CSR file in internal crypto format
    (result, buffer) = get_file_contents(arg_csr_path)
    if not result:
        app.logger.error("sign_csr: cannot access CSR {%s} for user {%s}, reason: {%s}", arg_csr_path, arg_userid, buffer)
        return False
    try:
        csr = crypto.load_certificate_request(crypto.FILETYPE_PEM, buffer)
    except Exception as e:
        app.logger.error("sign_csr: load CSR {%s} for user {%s} failed, reason: {%s}", arg_csr_path, arg_userid, repr(e))
        return False
    # CAcertificate = CA certificate in internal crypto format
    (result, buffer) = get_file_contents(CA_CRT_FILE)
    if not result:
        app.logger.error("sign_csr: cannot access CA certificate {%s} for user {%s}, reason: {%s}", CA_CRT_FILE, arg_userid, repr(e))
        return False
    try:
        CAcertificate = crypto.load_certificate(crypto.FILETYPE_PEM, buffer)
        if app.debug:
            app.logger.debug("sign_csr: CA cert subject = {%s}", CAcertificate.get_subject())
    except Exception as e:
        app.logger.error("sign_csr: load CA certificate {%s} for user {%s} failed, reason: {%s}", CA_CRT_FILE, arg_userid, repr(e))
        return False
    # CAprivatekey = CA private key in internal crypto format
    (result, buffer) = get_file_contents(CA_KEY_FILE)
    if not result:
        app.logger.error("sign_csr: cannot access CA private key {%s} for user {%s}, reason: {%s}", CA_KEY_FILE, arg_userid, buffer)
        return False
    try:
        CAprivatekey = crypto.load_privatekey(crypto.FILETYPE_PEM, buffer)
    except Exception as e:
        app.logger.error("sign_csr: load CA private key {%s} for user {%s} failed, reason: {%s}", CA_KEY_FILE, arg_userid, repr(e))
    # Sign CSR, giving the CRT
    try:
        cert = crypto.X509()
        cert.set_serial_number(get_serial())
        cert.gmtime_adj_notBefore(0)
        cert.gmtime_adj_notAfter(EXPIRY_PERIOD)
        cert.set_issuer(CAcertificate.get_subject())
        subject = csr.get_subject() # will log the subject later
        cert.set_subject(subject)
        cert.set_pubkey(csr.get_pubkey())
        cert.sign(CAprivatekey, DIGEST)
    except Exception as e:
        app.logger.error("sign_csr: Cannot sign CSR {%s} for user {%s}, reason: {%s}", arg_csr_path, arg_userid, repr(e))
        return False
    # Store signed CRT
    try:
        file = open(arg_crt_path, "w")
        file.write(crypto.dump_certificate(crypto.FILETYPE_PEM, cert).decode('utf-8'))
        file.flush()
        os.fsync(file)
        file.close()
    except Exception as e:
        app.logger.error("sign_csr: Cannot store CRT {%s} for user {%s}, reason: {%s}", arg_crt_path, arg_userid, repr(e))
        return False
    # Success
    app.logger.info("sign_csr: Success with CRT {%s} for user {%s}, subject={%s}", arg_csr_path, arg_userid, subject)
    return True

**Comment by texadactyl** [comment]
@au-squirrel - Your solution was just as valid as mine.  I went with a solution that got the job done yet was simple and provided random serial numbers (a good idea).  I tested on my machine.  When you get an opportunity, please test on yours.  Thank you.

**Comment by texadactyl** [comment]
@au-squirrel reports that he was able to observe random serial numbers.
